### ISSUE TITLE
WindowsError: [Error 2]

### ISSUE THREAD

**Issue by mrgloom** [cdcseacave/openMVS_sample#3]
I have tried to run pipeline demo, but get following error:

```
C:\Users\user\Downloads\openMVS_sample-master\openMVS_sample-master>python Mvg
Mvs_Pipeline.py images output
# Using input dir  :  C:\Users\user\Downloads\openMVS_sample-master\openMVS_sa
mple-master\images
#       output_dir :  C:\Users\user\Downloads\openMVS_sample-master\openMVS_sa
mple-master\output
# First step  :  0
# Last step :  11
#0. Intrinsics analysis
Traceback (most recent call last):
  File "MvgMvs_Pipeline.py", line 236, in <module>
    pStep = subprocess.Popen(cmdline)
  File "C:\Anaconda\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]
```

BTW, is there any linux demo same as this one?

**Comment by dudutingting** [comment]
I have the error the same as you ,do you resolve it now ?

**Comment by cdcseacave** [comment]
did you make sure the paths inside the scrip point to the OpenMVG and OpenMVS executables?

**Comment by dudutingting** [comment]
I do not  know,i just download the scrip from the website,whether the scrip need to modify and debug?
